export const GENRES = [
  "Action Adventure",
  "Action",
  "Adventure",
  "Alien Invasion",
  "American Gothic",
  "Atompunk",
  "Biopunk",
  "Black Comedy",
  "Body Horror",
  "Caper",
  "Climate Fiction",
  "Clockpunk",
  "Comedy",
  "Comic Fantasy",
  "Coming of Age",
  "Conspiracy and Paranoid Thriller",
  "Contemporary Fantasy",
  "Contemporary Romance",
  "Cosmic Horror",
  "Crime",
  "Cyberpunk",
  "Dark Fantasy",
  "Dark Romanticism",
  "Desert Island",
  "Detective Fiction",
  "Dieselpunk",
  "Disaster Thriller",
  "Drama",
  "Dramedy",
  "Dying Earth",
  "Dystopian",
  "Epic",
  "Fable",
  "Fairytale Fantasy",
  "Fantasy",
  "Fantasy Romance",
  "Financial Thriller",
  "Gaslamp Fantasy",
  "Ghost Story",
  "Gothic Fiction",
  "Grimdark",
  "Hard Fantasy",
  "Hard Science Fiction",
  "Hardboiled",
  "Heroic Fantasy",
  "High Fantasy",
  "Historical",
  "Historical Fantasy",
  "Historical Mystery",
  "Historical Romance",
  "Horror",
  "Horror Comedy",
  "Inverted Detective",
  "Legal Thriller",
  "Literary",
  "Lost World",
  "Low Fantasy",
  "Magic Realism",
  "Matron Literature",
  "Melodrama",
  "Military Science Fiction",
  "Monster Erotica",
  "Monster Literature",
  "Mystery",
  "Mythic Fiction",
  "Mythopoeia",
  "Mythpunk",
  "Nanopunk",
  "Nautical Fiction",
  "New Adult",
  "New Weird",
  "Noir",
  "Occult",
  "Occult Detective",
  "Parable",
  "Parallel Universe",
  "Paranoid",
  "Paranormal Romance",
  "Parody",
  "Philosophical",
  "Picaresque Novel",
  "Pirates",
  "Planetary Romance",
  "Police Procedural",
  "Political",
  "Political Thriller",
  "Pop Culture",
  "Post-Apocalyptic",
  "Prehistoric Fiction",
  "Psychological Horror",
  "Psychological Thriller",
  "Realist",
  "Regency Romance",
  "Romance",
  "Romantic Suspense",
  "Satire",
  "Science Fantasy",
  "Sci-Fi Comedy",
  "Sci-Fi",
  "Sci-Fi Romance",
  "Slasher",
  "Slice of Life",
  "Social Novel",
  "Social Science",
  "Soft Sci-Fi",
  "Solarpunk",
  "Southern Gothic",
  "Space Opera",
  "Space Western",
  "Speculative Fiction",
  "Spy Fiction",
  "Spy-fi",
  "Steampunk",
  "Steelpunk",
  "Stonepunk",
  "Subterranean Fiction",
  "Suburban Gothic",
  "Superhero",
  "Supernatural",
  "Survival",
  "Swashbuckler",
  "Sword and Planet",
  "Sword and Sorcery",
  "Tall Tale",
  "Tech-Noir",
  "Techno-Horror",
  "Techno-Thriller",
  "Thriller and Suspense",
  "Time-Travel Romance",
  "Tragedy",
  "Urban Fantasy",
  "Urban Fiction",
  "Urban Gothic",
  "Urban Legend",
  "Utopia",
  "Vampire",
  "Weird Fiction",
  "Weird West",
  "Werewolf",
  "Western",
  "Western Romance",
  "Whodunnit",
  "Young Adult",
  "Zombie Apocalypse",
  "Zombie Comedy",
];
